options:
  install_sources:
    type: string
    default: deb http://debian.neo4j.org/repo stable/
    description: |
      The repository to install Debian packages from.
  install_keys:
    type: string
    default: "01182252"
    description: |
      The key for the Debian package repository.
  python-driver-type:
    type: string
    default: "neo4j-driver"
    description: |
      This option will install a neo4j python driver. Supported drivers are Neo4J python driver(neo4j-driver)
      and Py2Neo(py2neo). Set to none if no driver has to be installed.
